export enum ENotificationType {
  ORDER_SUCCESS = 'ORDER_SUCCESS',
  ORDER_PENDING = 'ORDER_PENDING',
  ORDER_IN_PROGRESS = 'ORDER_IN_PROGRESS',
  ORDER_DELIVERING = 'ORDER_DELIVERING',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  ORDER_REFUND = 'ORDER_REFUND'
}
