export enum ESettingTypes {
  BANNER_HOME = 'BANNER_HOME',
  BANNER_CARD = 'BANNER_CARD',
  BANNER_GIFT = 'BANNER_GIFT',
  ADS_HOME = 'ADS_HOME',
  ADS_GIFT_OCCASION = 'ADS_GIFT_OCCASION',
  ADS_GIFT_FOR = 'ADS_GIFT_FOR',
  ADS_CARD_OCCASION = 'ADS_CARD_OCCASION',
  ADS_CARD_FOR = 'ADS_CARD_FOR'
}
